on: [workflow_dispatch]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Godot
        uses: ./
        version: 4.0
        prerelease_version: beta16